# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  apiUrl: 'wiseflux-backend-prod.azurewebsites.net'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.9.0'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    echo "Listing contents of dist directory:"
    ls -l $(System.DefaultWorkingDirectory)/dist
  displayName: 'List build output'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- script: |
    echo "Listing contents of the zip archive:"
    unzip -l $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  displayName: 'List contents of archive'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(1)(38c5c508-1dee-43c3-bceb-43a462cbfb4d)'
    appType: 'webAppLinux'
    WebAppName: 'wiseflux-prod'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
